//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập trang quản trị.
        /// </summary>
        public static string Admin_Login {
            get {
                return ResourceManager.GetString("Admin_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục.
        /// </summary>
        public static string Category_Management {
            get {
                return ResourceManager.GetString("Category_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string Content_New {
            get {
                return ResourceManager.GetString("Content_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý khoá học.
        /// </summary>
        public static string Course_Management {
            get {
                return ResourceManager.GetString("Course_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Bởi.
        /// </summary>
        public static string Create_By {
            get {
                return ResourceManager.GetString("Create_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới tin tức.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string Day_Create {
            get {
                return ResourceManager.GetString("Day_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý đề thi.
        /// </summary>
        public static string Exam_Management {
            get {
                return ResourceManager.GetString("Exam_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý bài giảng.
        /// </summary>
        public static string Lesson_Management {
            get {
                return ResourceManager.GetString("Lesson_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách danh mục.
        /// </summary>
        public static string List_Categories {
            get {
                return ResourceManager.GetString("List_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách khoá học.
        /// </summary>
        public static string List_Course {
            get {
                return ResourceManager.GetString("List_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đề thi.
        /// </summary>
        public static string List_Exam {
            get {
                return ResourceManager.GetString("List_Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bài giảng.
        /// </summary>
        public static string List_Lesson {
            get {
                return ResourceManager.GetString("List_Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dánh sách tin tức.
        /// </summary>
        public static string List_New {
            get {
                return ResourceManager.GetString("List_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách câu hỏi.
        /// </summary>
        public static string List_Question {
            get {
                return ResourceManager.GetString("List_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Meta_Title {
            get {
                return ResourceManager.GetString("Meta_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tin tức.
        /// </summary>
        public static string New_Management {
            get {
                return ResourceManager.GetString("New_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Tin Tức.
        /// </summary>
        public static string New_Name {
            get {
                return ResourceManager.GetString("New_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Photo_Image {
            get {
                return ResourceManager.GetString("Photo_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý câu hỏi.
        /// </summary>
        public static string Question_Management {
            get {
                return ResourceManager.GetString("Question_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        public static string Sign_Name {
            get {
                return ResourceManager.GetString("Sign_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng tạo.
        /// </summary>
        public static string User_Create {
            get {
                return ResourceManager.GetString("User_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
